### PR TITLE
GORA_447 NPE Fix

### PR DESCRIPTION
**Pull request by djkevincr**

### CODE REVIEW

**Comment by lewismc** [comment]
@djkevincr thanks for this PR. 
Some hints; when you open an issue here and make your commit message, if you are able to make the JIRA issue and Commit message the same, then all correspondence will be shadowed over to the JIRA ticket automatically. 
I'll check this PR out ASAP. Thanks

**Comment by djkevincr** [comment]
@lewismc Thanks for the hints, will make sure those are followed from next time. Please review and let me know if there any concerns.

**Comment by lewismc** [comment]
@renato2099 any comments here?

**Comment by renato2099** [comment]
it's pretty cool stuff @djkevincr ! But I think we need to go over it. My main concern is the addition of the clearField method to the Persistent class. Two main thoughts on it:
- We should try to keep the main Persistent API as stable as possible because we have some dependencies on it e.g. goraCompiler, and therefore all the avro generated beans we create from it. 
- This method is proposed for clearing the values of MemStore. So it would seem that only MemStore needs it. So I am not sure we need to add it to main API. Why don't we use a method like getPersistent? What do you guys think @lewismc @djkevincr ?
The other thing that I think we need to change is how the deleteByQuery is working now. I mean it's great that is not breaking anymore :D but I think we need and IfElse stmt after the if(allFields) because if we have deleted the specific key, then why do we need to iterate through the fields?

**Comment by djkevincr** [comment]
@renato2099 +1, I also agree with your concerns. However I had to make some changes to  MemStore getPersistent(T obj, String[] fields) to work as expected. I have further added some test cases to verify this method. Can you please have look?

**Comment by djkevincr** [comment]
@lewismc @renato2099 Is there anything which I could help here?

**Comment by lewismc** [comment]
We need to ensure that the additions to the persistent class/compiler do not render data which has already been written useless!

**Comment by djkevincr** [comment]
@lewismc +1 I have removed all the changes I did to Persistent class/compiler as per the @renato2099 review. I added some changes to deleteByQuery(Query<K, T> query)  and getPersistent(T obj, String[] fields) of MemStore. Further I added some unit tests for getPersistent(T obj, String[] fields) to MemStoreTest. Can you please point me to the code if anything I am missing here ?

**Comment by lewismc** [comment]
I am +1 for this patch. Any comments @renato2099

**Comment by lewismc** [comment]
Thank you @djkevincr if you could 
1) name your commit message and hence Github issue after the Jira ticket, it means the Github hooks work perfectly.
2) Squash your commits into one if possible.
Thank you very much @djkevincr

**Comment by renato2099** [comment]
Thanks @lewismc @djkevincr ! This looks much more to what we needed :D Awesome work!

**Pull request merged**
