### PR TITLE
GORA-394 Resolve erroneous error logging in reading HBase mapping file

### PR DESCRIPTION
**Pull request by nishadi**
This PR resolves erroneous error logging in reading HBase mapping file as stated in the issue

### CODE REVIEW

**Comment by lewismc** [comment]
@alfonsonishikawa can you check this out? I am not using HBase at this moment... if you cannot I will pull the source for HBase and try it out. 

@nishadi I've looked at the PR and it looks good to me, however I wonder if there is a small test we could include for the [HBaseStore#readMapping](https://github.com/apache/gora/blob/master/gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java#L730) which would allow us to verify the behavior? Well annotated unit tests, specifically on individual datastores are very useful for datastore-specific behaviour. 
Thank you for the PR, this is great.

**Comment by djkevincr** [comment]
+1 for merge to master, will let others to review. Thanks for contribution @nishadi Good work :)

**Comment by nishadi** [comment]
You are welcome :) I am working on the test case.

**Comment by alfonsonishikawa** [comment]
Hi!

I don't find necessary to have tests on this issue. The reason is that the issue is about a wrong placed logging -the need to move it out of the `for`-, so I don't find anything to test and the fix looks perfect.

+1 to merge to master, since it solves https://issues.apache.org/jira/browse/GORA-394 perfectly.

I suggest, as a later improvement in other issue, to discuss if it is suitable to throw an exception after logging (fail fast when the configuration is wrong) - and in this case a test will be needed, of couse :) -

@nishadi, thanks for the fix!

**Comment by renato2099** [comment]
+1 to what @alfonsonishikawa said 
Thanks @nishadi  for the patch! :)

**Comment by alfonsonishikawa** [comment]
If no one objects, I will commit this in a while :)

**Comment by renato2099** [comment]
👍

**Comment by madhawa-gunasekara** [comment]
What will happened if second class didn't match?

**Comment by alfonsonishikawa** [comment]
Commited, thank you very much, @nishadi .

@madhawa-gunasekara : What was happening is that it was showing one message for each class not matching even when there were one class matching in all the classes list. The objective was to show only one message if neither of the classes matched. I commited at the same time as you commented :S Are you thinking about something I missed?

**Comment by madhawa-gunasekara** [comment]
@alfonsonishikawa thanks for the explanation. :+1:

**Comment by nishadi** [comment]
Thank you for merging :)

**Pull request merged**
