### PR TITLE
GORA-471 Datastore for Infinispan

### PR DESCRIPTION
**Pull request by lewismc**
This PR addresses https://issues.apache.org/jira/browse/GORA-471
The issue was originally proposed over on https://github.com/leads-project/gora-infinispan/issues/1
Absolute Kudos to the people over at the LEEDS-PROJECT and also on the CLOUD computing paper they put together to describe how they are using this module for cool sh*t.
@otrack please check out this PR and see what you think. All I have done is smarten it up a bit e.g. include license headers on all relevant files. 
The one issue, is that the dependency at https://github.com/leads-project/infinispan-avro needs to be pushed to Maven central or installed locally on every node that wish to use this module.
We need to work on pushing https://github.com/leads-project/infinispan-avro to Maven central before we can merge this pull request.
Kudos again to all authors of this work, this work is not mine.

### CODE REVIEW

**Comment by renato2099** [comment]
Really cool for sure :+1:

**Comment by otrack** [comment]
Once this version is merged, I can do a few modifications; namely, (i) changing infinispan-avro to the now publicly released 1.0.Final, (ii) smoothing the README file and (iii) adding some instructions about how to start an ISPN server easily.

**Comment by lewismc** [comment]
Hi @otrack nice, thanks. Good work on getting the infinispan-avro dependency pushed to Central.
I've committed this branch to master, if you could help to stabilize it would be appreciated.
Thanks

**Comment by renato2099** [comment]
Thanks @otrack ! Great work indeed!

**Comment by lewismc** [comment]
hi @otrack I've committed the module to Gora master branch and also made an update to the dependency versions to accommodate the shift to 1.0 and 1.0.Final. 
Thanks for push these up to Maven Central. Once the build stabilizes, if you are able to open any tickets over at https://issues.apache.org/jira/browse/GORA before sending any pull requests it would be greatly appreciated.
Thanks

**Comment by otrack** [comment]
Hi @lewismc, In the current state, I have integrated everything and the tests are passing properly. What I would like, before submitting the changes (via a pull request), is to give an insight on how deploying the server part of infinispan-avro. There will be a link to this explanation in the README.md file.

**Comment by lewismc** [comment]
@otrack sounds excellent.
Thanks

**Pull request merged**
