### PR TITLE
GORA-560:Fix Java doc comments to stabalize the build

### PR DESCRIPTION
**Pull request by madhawa-gunasekara**

### CODE REVIEW

**Comment by madhawa-gunasekara** [comment]
@djkevincr Can you review and merge this pull request.

**Comment by djkevincr** [comment]
`[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Gora ........................................ SUCCESS [ 29.755 s]
[INFO] Apache Gora :: Compiler ............................ SKIPPED
[INFO] Apache Gora :: Compiler-CLI ........................ SKIPPED
[INFO] Apache Gora :: Core ................................ SKIPPED
[INFO] Apache Gora :: Pig ................................. SKIPPED
[INFO] Apache Gora :: Accumulo ............................ SKIPPED
[INFO] Apache Gora :: HBase ............................... SKIPPED
[INFO] Apache Gora :: Cassandra - CQL ..................... SKIPPED
[INFO] Apache Gora :: GoraCI .............................. SKIPPED
[INFO] Apache Gora :: Infinispan .......................... SKIPPED
[INFO] Apache Gora :: JCache .............................. SKIPPED
[INFO] Apache Gora :: OrientDB ............................ SKIPPED
[INFO] Apache Gora :: Lucene .............................. SKIPPED
[INFO] Apache Gora :: Dynamodb ............................ SKIPPED
[INFO] Apache Gora :: CouchDB ............................. SKIPPED
[INFO] Apache Gora :: Maven Plugin ........................ SKIPPED
[INFO] Apache Gora :: MongoDB ............................. SKIPPED
[INFO] Apache Gora :: Solr ................................ SKIPPED
[INFO] Apache Gora :: Aerospike ........................... SKIPPED
[INFO] Apache Gora :: Ignite .............................. SKIPPED
[INFO] Apache Gora :: Tutorial ............................ SKIPPED
[INFO] Apache Gora :: Sources-Dist ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.506 s
[INFO] Finished at: 2019-03-24T21:59:07+05:30
[INFO] Final Memory: 105M/1409M
[INFO] ------------------------------------------------------------------------
`

**Comment by djkevincr** [comment]
+1, mvn javadoc:aggregate build without any issue.

**Comment by djkevincr** [comment]
This is great @madhawa-gunasekara , I have merged your PR. Thank you for the contribution.

**Comment by alfonsonishikawa** [comment]
@madhawa-gunasekara So sorry for the javadoc bugs :( Thank you very much for fixing it!

I will add to my own development procedures to execute `mvn javadoc:javadoc` before creating the pull request.

**Pull request merged**
