### PR TITLE
Fix typo in pom.xml

### PR DESCRIPTION
**Pull request by claudeyj**

### CODE REVIEW

**Review by drazzib — APPROVED** [review]
Hi @claudeyj 
Thank you for correcting the typos

**Comment by claudeyj** [comment]
Thank you for reviewing this PR. I found there's another related typo here that should be fixed together: https://github.com/apache/gora/blob/2cccfdbed4fe72668660177572e1d24ed137b88b/gora-sql/pom.xml#L110.

**Comment by drazzib** [comment]
> Thank you for reviewing this PR. I found there's another related typo here that should be fixed together:
> 
> https://github.com/apache/gora/blob/2cccfdbed4fe72668660177572e1d24ed137b88b/gora-sql/pom.xml#L110

Could you please push additional commits which include this change ?

**Comment by claudeyj** [comment]
It's done now.

**Pull request merged**
