### PR TITLE
GORA-536: Avoid calling Class#newInstance

### PR DESCRIPTION
**Pull request by carlosrmng**
When using reflexion use `getDeclaredConstructor().newInstance()` instead of `Class::newInstance` because it may throw undeclared checked exceptions.

### CODE REVIEW

**Comment by djkevincr** [comment]
This looks good :) Thanks for the PR Carlos. Will keep other s to review as well. If no one have concerns, I will proceed merging this to the master.

**Comment by carlosrmng** [comment]
Hi @lewismc
I found multiple classes and interfaces that define their own newInstance() method which are not directly affected by the issue. I used my IDE's 'find usages' feature to search for all the Class#newInstance() references within the code, so hopefully I didn't miss anything.

Some examples:
- [javax.xml.parsers.DocumentBuilderFactory#newInstance()](https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilderFactory.html#newInstance())
- [org.apache.gora.persistency.Persistent#newInstance()](https://github.com/apache/gora/blob/dc70b14b542830cee434329cabee1b801ad51254/gora-core/src/main/java/org/apache/gora/persistency/Persistent.java#L115)
- [org.apache.gora.goraci.generated.CINode#newInstance()](https://github.com/apache/gora/blob/dc70b14b542830cee434329cabee1b801ad51254/gora-goraci/src/main/java/org/apache/gora/goraci/generated/CINode.java#L342)

**Comment by lewismc** [comment]
+1 @djkevincr please merge

**Comment by djkevincr** [comment]
@carlosrmng As we discussed offline, Can you please update the PR?

**Comment by djkevincr** [comment]
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Gora ....................................... SUCCESS [1.296s]
[INFO] Apache Gora :: Compiler ........................... SUCCESS [2.198s]
[INFO] Apache Gora :: Compiler-CLI ....................... SUCCESS [1.214s]
[INFO] Apache Gora :: Core ............................... SUCCESS [1:26.668s]
[INFO] Apache Gora :: Accumulo ........................... SUCCESS [7:20.811s]
[INFO] Apache Gora :: HBase .............................. SUCCESS [2:31.169s]
[INFO] Apache Gora :: Cassandra - CQL .................... SUCCESS [1:20.393s]
[INFO] Apache Gora :: GoraCI ............................. SUCCESS [6.215s]
[INFO] Apache Gora :: Infinispan ......................... SUCCESS [1:09.991s]
[INFO] Apache Gora :: JCache ............................. SUCCESS [56.084s]
[INFO] Apache Gora :: OrientDB ........................... SUCCESS [1:35.556s]
[INFO] Apache Gora :: Dynamodb ........................... SUCCESS [4.308s]
[INFO] Apache Gora :: CouchDB ............................ SUCCESS [4.313s]
[INFO] Apache Gora :: Maven Plugin ....................... SUCCESS [3.132s]
[INFO] Apache Gora :: MongoDB ............................ SUCCESS [1:27.104s]
[INFO] Apache Gora :: Solr ............................... SUCCESS [3:48.569s]
[INFO] Apache Gora :: Aerospike .......................... SUCCESS [2.391s]
[INFO] Apache Gora :: Tutorial ........................... SUCCESS [4.992s]
[INFO] Apache Gora :: Sources-Dist ....................... SUCCESS [0.568s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:07.628s
[INFO] Finished at: Tue May 22 17:00:41 IST 2018
[INFO] Final Memory: 83M/786M

**Comment by djkevincr** [comment]
This is great @carlosrmng Thank you very much for the PR :)

**Pull request merged**
