### PR TITLE
 GORA-554: Upgrade Solr dependency to latest

### PR DESCRIPTION
**Pull request by djkevincr**
This PR Upgrade Solr dependency to 8.0.0. Plus all the deprecated methods are removed from usages.

### CODE REVIEW

**Comment by djkevincr** [comment]
@madhawa-gunasekara Will you be able to review the PR?

**Comment by madhawa-gunasekara** [comment]
@djkevincr This is awesome, However If we can configure the queue size and thread count for the concurrent, that will be perfect. So users can configure these two properties based on the performance they require. What do you think ?

**Comment by djkevincr** [comment]
+1, Yes it was hard coded before, will add to same PR.

**Comment by djkevincr** [comment]
@madhawa-gunasekara Updated the PR. Can you please have a look and merge the PR.

**Comment by madhawa-gunasekara** [comment]
I tested locally, all good.
```
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 82, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.3:bundle (default-bundle) @ gora-solr ---
[INFO] 
[INFO] --- maven-site-plugin:3.7.1:attach-descriptor (attach-descriptor) @ gora-solr ---
[INFO] Skipping because packaging 'bundle' is not pom.
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy-dependencies (copy) @ gora-solr ---



[INFO] Installing /home/madhawa/gora/sources-dist/target/apache-gora-0.9-SNAPSHOT-src.tar.gz to /home/madhawa/.m2/repository/org/apache/gora/sources-dist/0.9-SNAPSHOT/sources-dist-0.9-SNAPSHOT-src.tar.gz
[INFO] Installing /home/madhawa/gora/sources-dist/target/apache-gora-0.9-SNAPSHOT-src.zip to /home/madhawa/.m2/repository/org/apache/gora/sources-dist/0.9-SNAPSHOT/sources-dist-0.9-SNAPSHOT-src.zip
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Gora 0.9-SNAPSHOT:
[INFO] 
[INFO] Apache Gora ........................................ SUCCESS [04:08 min]
[INFO] Apache Gora :: Compiler ............................ SUCCESS [ 38.032 s]
[INFO] Apache Gora :: Compiler-CLI ........................ SUCCESS [  1.538 s]
[INFO] Apache Gora :: Core ................................ SUCCESS [05:33 min]
[INFO] Apache Gora :: Pig ................................. SUCCESS [ 36.047 s]
[INFO] Apache Gora :: Accumulo ............................ SUCCESS [16:37 min]
[INFO] Apache Gora :: HBase ............................... SUCCESS [05:15 min]
[INFO] Apache Gora :: Cassandra - CQL ..................... SUCCESS [06:24 min]
[INFO] Apache Gora :: GoraCI .............................. SUCCESS [ 30.014 s]
[INFO] Apache Gora :: Infinispan .......................... SUCCESS [02:24 min]
[INFO] Apache Gora :: JCache .............................. SUCCESS [01:29 min]
[INFO] Apache Gora :: OrientDB ............................ SUCCESS [02:04 min]
[INFO] Apache Gora :: Lucene .............................. SUCCESS [01:28 min]
[INFO] Apache Gora :: Dynamodb ............................ SUCCESS [ 49.611 s]
[INFO] Apache Gora :: CouchDB ............................. SUCCESS [ 41.710 s]
[INFO] Apache Gora :: Maven Plugin ........................ SUCCESS [ 19.499 s]
[INFO] Apache Gora :: MongoDB ............................. SUCCESS [06:55 min]
[INFO] Apache Gora :: Solr ................................ SUCCESS [08:48 min]
[INFO] Apache Gora :: Aerospike ........................... SUCCESS [  9.409 s]
[INFO] Apache Gora :: Ignite .............................. SUCCESS [01:25 min]
[INFO] Apache Gora :: Tutorial ............................ SUCCESS [ 27.670 s]
[INFO] Apache Gora :: Sources-Dist ........................ SUCCESS [  4.935 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 h
[INFO] Finished at: 2019-03-24T02:40:21+05:30
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
