### PR TITLE
GORA-675: Perform Sonar static code analysis on Jenkins

### PR DESCRIPTION
**Pull request by drazzib**

### CODE REVIEW

**Comment by lewismc** [comment]
The Jenkinsfile looks good but of-course the build failed with NPE...

**Comment by lewismc** [comment]
+1 for merge into master branch @drazzib

**Review by lewismc — APPROVED** [review]
+1

**Comment by djkevincr** [comment]
+1, @lewismc I will help you with PR merging.

**Comment by drazzib** [comment]
Thanks @lewismc @djkevincr !
I'll take care of merging into master.

**Pull request merged**
