### PR TITLE
GORA-530: Removed redundant logging on several try/catch

### PR DESCRIPTION
**Pull request by alfonsonishikawa**
Hi!
In this patch basically I removed the redundand "logging + throw" when the log message is the same as in the exception.
Sorry for the mess of two pull requests :(
Please comment anything you find that don't convice you.

Thanks!

https://issues.apache.org/jira/browse/GORA-530

### CODE REVIEW

**Comment by renato2099** [comment]
Hi @alfonsonishikawa , thanks for doing this!
I think the first option was also ok because one thing is logging what the problem was and other throwing the exception for the application using Gora to deal with it as it fits better to the application.
what do you think @lewismc ?

**Comment by lewismc** [comment]
@alfonsonishikawa @renato2099 I think this looks good. Tidies up Exception handling quite nicely.

**Comment by lewismc** [comment]
@alfonsonishikawa can you commit to master?

**Comment by alfonsonishikawa** [comment]
Done, thank you!

**Comment by alfonsonishikawa** [comment]
I can't believe how sausage-fingers I must be. I left a strange Eclipse autoimport at https://github.com/apache/gora/blob/master/gora-core/src/main/java/org/apache/gora/persistency/impl/BeanFactoryImpl.java#L28 . If you don't mind, I will straight delete it, test and push without a pull request -it is not being used, safe-. How embarrassing. Sorry.

**Comment by lewismc** [comment]
+1

**Pull request merged**
