### PR TITLE
GORA-362 Refactor gora-dynamodb to support avro serialization

### PR DESCRIPTION
**Pull request by lewismc**
Hi @renato2099 OK here it is in all of it's glory... and what a patch it is!
This is a beast!
I've tested it locally and all working well. I updated a number of areas, fixed a few bugs and also made the patch compliant with the forbidden api's checks. 
This issue relates to https://issues.apache.org/jira/browse/GORA-362
What an effort this was by you first time around... kudos mate.

### CODE REVIEW

**Comment by renato2099** [comment]
This is awesome mate! I really thought I had lost this.
Maybe we can commit this as an initial patch and start working from there? wdyt @lewismc ?

**Comment by lewismc** [comment]
I am +1 for it. In it's current state e.g. master, gora-dynamodb is kinda broken, It is also severaly behind the aws java SDK meaning that I am not even sure we can persist data into dynamodb anymore.
I would be +1 for committing this patch, it tests, it builds ,etc.
Anyone else have comments?

**Comment by renato2099** [comment]
yeah I think we can at least start moving that direction :+1:

**Comment by renato2099** [comment]
there still some more work to get it done, but I think we are moving in the right direction with this :)

**Pull request merged**
