### PR TITLE
GORA-498 Adding mongodb authentications

### PR DESCRIPTION
**Pull request by madhawa-gunasekara**

### CODE REVIEW

**Comment by lewismc** [comment]
@alfonsonishikawa do you have any further comments on this one? I would like to merge it into master if you are OK.

**Comment by lewismc** [comment]
@madhawa-gunasekara It would be good if you could augment the Javadoc by providing the actual string names for the authentication types. This way we can easily add it to the canonical documentation at http://gora.apache.org/current/gora-mongodb.html

**Comment by madhawa-gunasekara** [comment]
@lewismc :+1:  I will do like that

**Comment by lewismc** [comment]
Thank you, this way we know the options. Thank you very much.

**Comment by alfonsonishikawa** [comment]
@lewismc I see the patch breaking older configurations when maybe we can avoid it:
The method MongoCredential.createCredential() now does not work? If it still works, it will be good to use MongoCredential.createCredential() as the default configuration if an user/pass has been specified but not auth method (this is: older configurations having only user/pass configured).
I would be glad to pull after.

I commented at https://issues.apache.org/jira/browse/GORA-498 but now I see it was not delivering emails to many people :S

**Comment by madhawa-gunasekara** [comment]
@alfonsonishikawa, yes sure. I will update the pull request. btw I have written the test case for this scenario. I will send the changes with that as well.

**Comment by alfonsonishikawa** [comment]
@madhawa-gunasekara Great! Thank you!

**Comment by madhawa-gunasekara** [comment]
@alfonsonishikawa @lewismc I have added automation tests and JavaDoc comments

**Comment by lewismc** [comment]
Any more comments @alfonsonishikawa ?

**Comment by lewismc** [comment]
@alfonsonishikawa ping

**Comment by drazzib** [comment]
Hi @all !
[back to Gora MongoDB after some time offline :]

I've reviewed proposed code and it looks good to me.
IMHO, this could be merged for 0.7 release.

Regards,

**Comment by alfonsonishikawa** [comment]
@lewismc Sorry! I have been much busy and ill after :( Thank you for the merge.
Sorry!! :(

**Pull request merged**
