### PR TITLE
Setting dirty with value -1 (11111111b) instead of -128(1000000b) whe…

### PR DESCRIPTION
**Pull request by alfonsonishikawa**
…n calling setDirty().

Omited tests since the change is trivial.

### CODE REVIEW

**Comment by lewismc** [comment]
Any test?

**Comment by alfonsonishikawa** [comment]
For once I assumed it was too trivial for a test... ;)

I am working on it.

I noticed that maybe someone sometime would need a "setDirty" that sets dirty deep in the hierarchical data, and not only the shallow fields. But this is not the issue :)

**Comment by alfonsonishikawa** [comment]
Updated with the test :) Thanks for the feedback.

**Comment by lewismc** [comment]
+1 LGTM

**Pull request merged**
