### PR TITLE
Gradle plugin for Apache Gora (GORA-330)

### PR DESCRIPTION
**Pull request by drazzib**
I've finally took some time to offer a clean PR to merge my Gradle plugin (see GORA-330 for details).

### CODE REVIEW

**Comment by hsaputra** [comment]
Hi @drazzib, could you create JIRA account for this PR?

**Comment by hsaputra** [comment]
Ah I was an idiot =P

Never mind =)

**Comment by drazzib** [comment]
Hi @lewismc 

I've pushed ASL 2.0 headers on some more files but haven't proceed all :
- gradlew + gradlew.bat + gradle/wrapper/* are auto-generated from Gradle build system
- examples/simple/src/main/resources/test1.avsc It seems we can't add comment into Gora Schema files ? Am I wrong ?

I'm okay for pushing this to master now but it should be noted that it's still WiP (for instance, there is no real configuration for source / destination directories)

**Comment by lewismc** [comment]
Hi @drazzib 
RE: license headers, great
RE: Gora Schema files, yes you are correct this is absolutely fine
+1 for commit to master branch. If you are keen and able, please feel free to set up an additional build job on builds.apache.org if you have tests for the plugin which you would like to run.

**Pull request closed without merging**
