### PR TITLE
GORA-324 Port work done on old GoraCompiler to new GoraCompiler

### PR DESCRIPTION
**Pull request by nishadi**
This PR includes enhancements to the gora-compiler as follows.

- add license headers to generated files

- add the ability to compile files in a directory.

### CODE REVIEW

**Comment by nishadi** [comment]
Hi, Thank you. I have amended the formatting fixes to the existing commit.

**Comment by lewismc** [comment]
+1 to merge to master... anyone else want to review? Thank you @nishadi

**Comment by djkevincr** [comment]
+1 from my end as well, great work @nishadi :) Thank you for the contribution.

**Comment by lewismc** [comment]
Thank you @nishadi merged into master branch

**Comment by nishadi** [comment]
Thank you for merging :)

**Pull request merged**
