### PR TITLE
GORA-228 GORA-226 Memstore problems is fixed

### PR DESCRIPTION
**Pull request by cguzel**
GORA-228 GORA-226 Memstore problems is fixed

### CODE REVIEW

**Comment by lewismc** [comment]
Has this been tested? How can we test this out? Thank you @cguzel for the patch it is excellent to see MemStore being fied :+1:

**Comment by cguzel** [comment]
Yes I tested on nutch. The Nutch Injector test is run successfully . You can apply the last patch from NUTCH-1741 and run TestInjector.java

**Comment by lewismc** [comment]
Any objections to committing this patch folks? @hsaputra you mentioned over on [GORA-228]() that ..."my proposal is to remove the static reference of the MemStore by having multiple MemStores instances that could be used in different threads as mentioned by @renato2099  in the previous comment. We fixed the ConcurrentModificationException by doing this."
Do you want to implement this or tackle this in a different issue if and when it arises. Right now it seems that we just need to fix the Jira issue, not add functionality for something which may occur in the future. wdyt?

**Comment by hsaputra** [comment]
@lewismc lets push this in and follow up later. This at least solve multiple threads issues with memstore.

**Comment by renato2099** [comment]
+1

**Pull request closed without merging**
