### PR TITLE
GORA-430 Address use of deprecated API's

### PR DESCRIPTION
**Pull request by podorvanova**
There are a couple of issues I faced with:
1) Is it ok to remove `allowRemoteDCsForLocalConsistencyLevel` completely like I did? The docs say "DC failover shouldn't be done in the driver, which does not have the necessary context to know what makes sense considering application semantics", so it probably does not make sense to keep this as an option in gora.
2) Datastax developers [decided to remove](https://docs.datastax.com/en/developer/java-driver/3.5/upgrade_guide/#3-5-0) `DowngradingConsistencyRetryPolicy` adding that users will now have to implement this logic themselves. It is probably possible to implement something analogous to their [example](https://github.com/datastax/java-driver/blob/3.x/driver-examples/src/main/java/com/datastax/driver/examples/retry/DowngradingRetry.java), but I think that  its impementation is out of this ticket's scope, so I just removed it too.

### CODE REVIEW

**Comment by lewismc** [comment]
Thank you @podorvanova 
Is anyone able to verify the Cassandra datastore ?

**Comment by madhawa-gunasekara** [comment]
Hi @podorvanova, 

Thanks for the pull request. I would like to see "allowRemoteDCsForLocalConsistencyLevel" to remain in the gora.properties file. because if someone needs to create two Cassandra Datastores then he can use two separate gora.properties files. that's why we get rid of the cassandra application.conf file, where we put it in the classpath.

**Comment by podorvanova** [comment]
Hi @madhawa-gunasekara,

Do I understand correctly that I should leave `allowRemoteDCsForLocalConsistencyLevel()`, even though it is deprecated?

**Comment by madhawa-gunasekara** [comment]
Hi @podorvanova, 

No, You are right. just removed. it's deprecated.

**Comment by madhawa-gunasekara** [comment]
merged to the master. Thanks, @podorvanova for your contribution

**Pull request merged**
