### PR TITLE
GORA-255 Remove deprecated methods from data store test base

### PR DESCRIPTION
**Pull request by nishadi**
This PR removes the deprecated methods from data store test base.

### CODE REVIEW

**Comment by lewismc** [comment]
+1 can someone do the honors of merging into master please?

**Comment by djkevincr** [comment]
@lewismc Will merge it to the master. @nishadi Thanks for the PR. This is great :)

**Comment by djkevincr** [comment]
Merged the PR, thank you very much @nishadi :)

**Comment by nishadi** [comment]
Thank you for merging :)

**Pull request merged**
