### PR TITLE
Gora 409 tutorial

### PR DESCRIPTION
**Pull request by djkevincr**
@lewismc I have added new tutorial class ( DistributedLogManager.java ) and I have added few fixes for the issues encountered while testing the module. Please go through the sample and let me know what you think and I could add some changes accordingly. If you could give me access to Apache-Gora site, I could add some documentation there as well.

### CODE REVIEW

**Comment by lewismc** [comment]
Thanks @djkevincr I will review.
For the time being, the site source can be found at http://svn.apache.org/repos/asf/gora/site/
Thanks

**Comment by lewismc** [comment]
Please take a look at the Javadoc you've added to DistrobutedLogManager. It needs to be improved.
screen shot 2016-08-14 at 3 46 15 pm

Please format it correctly with the correct enumeration for the list items, code examples, etc.

**Comment by djkevincr** [comment]
@lewismc I have fixed the formatting issues. Can you please have a look?

**Comment by lewismc** [comment]
Thanks @djkevincr , I haven't seen any updates to the [bin/gora](https://github.com/apache/gora/blob/master/bin/gora) script. Can you please make the relevant trivial updates such that DistributedLogManager is easily accessible to users from the command line? Thanks, once this is done we can merge to master. Good work.

**Comment by djkevincr** [comment]
@lewismc I have pushed the changes related to bin/gora script.

**Pull request merged**
