### PR TITLE
GORA-266 Lucene datastore for Gora - lewismc

### PR DESCRIPTION
**Pull request by djkevincr**
This is based on https://github.com/apache/gora/pull/131 resolved conflicts and merged to master. However tests needs to be fixed.

### CODE REVIEW

**Comment by lewismc** [comment]
I think this looks good. The only suggestion I have right now is to expand support for other `keyClass` implementations in LuceneQuery. There is currently a comment for NumericRangeQuery... maybe we can address this in a future pull request?

**Comment by djkevincr** [comment]
@lewismc I have created issue [1] on NumericRangeQuery. I think this PR is in good shape to be merged.
All major test cases passes without any issue. 
[1] https://issues.apache.org/jira/browse/GORA-555

**Comment by lewismc** [comment]
+1 @djkevincr

**Comment by djkevincr** [comment]
@lewismc I have merged the PR. Thank you very much for your hard work on implementation and reviewing PR.

**Pull request merged**
