### PR TITLE
GORA-459

### PR DESCRIPTION
**Pull request by renato2099**
Fixing HBaseClusterSingleton.java unclosed resources returned from HBaseTestingUtility

### CODE REVIEW

**Comment by lewismc** [comment]
+1

On Sunday, January 17, 2016, Renato Marroquin <notifications@github.com>
wrote:

> Fixing HBaseClusterSingleton.java unclosed resources returned from
> HBaseTestingUtility
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apache/gora/pull/51
> Commit Summary
>
>    - GORA-459
>
> File Changes
>
>    - *M*
>    gora-hbase/src/test/java/org/apache/gora/hbase/util/HBaseClusterSingleton.java
>    <https://github.com/apache/gora/pull/51/files#diff-0> (7)
>
> Patch Links:
>
>    - https://github.com/apache/gora/pull/51.patch
>    - https://github.com/apache/gora/pull/51.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/gora/pull/51>.
>


-- 
*Lewis*

**Comment by renato2099** [comment]
Can you commit this and the other PRs @lewismc please? I don't know why I don't have right to actually do the merging myself. Thanks man!

**Comment by lewismc** [comment]
Yeah I can but it would be good to sort the commit issue out.
Are your trying to commit to the Git repos or the Github mirror?

On Monday, January 18, 2016, Renato Marroquin <notifications@github.com>
wrote:

> Can you commit this and the other PRs @lewismc
> <https://github.com/lewismc> please? I don't know why I don't have right
> to actually do the merging myself. Thanks man!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/gora/pull/51#issuecomment-172539082>.
>


-- 
*Lewis*

**Comment by renato2099** [comment]
I can commit through the cmd line git commands, but I can't merge the PR from the github website, can you do that? or do you the commits directly from the cmd line?

**Comment by lewismc** [comment]
Yeah it's all commits through the CLI to the canonical source at Apache. As
the Github mirror is not canonical source, the merge functionality is
disabled.

On Monday, January 18, 2016, Renato Marroquin <notifications@github.com>
wrote:

> I can commit through the cmd line git commands, but I can't merge the PR
> from the github website, can you do that? or do you the commits directly
> from the cmd line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/gora/pull/51#issuecomment-172680924>.
>


-- 
*Lewis*

**Comment by renato2099** [comment]
got it, then you wanna merge? or should I? :+1:

**Comment by lewismc** [comment]
If you can then please go ahead. I'm out and about now.
I'll merge this into my HBase branch and submit a PR once it's ready.
Thanks Renato.

On Monday, January 18, 2016, Renato Marroquin <notifications@github.com>
wrote:

> got it, then you wanna merge? or should I? [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/gora/pull/51#issuecomment-172681580>.
>


-- 
*Lewis*

**Pull request closed without merging**
