### PR TITLE
GORA-439 Remove Unused Method Parameters

### PR DESCRIPTION
**Pull request by kamaci**
Unused method parameters are removed and API signatures made clean.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @kamaci I had a look through the patch. Please make sure that there are no regressions. I am +1 to commit if this is the case.

**Comment by renato2099** [comment]
I am in favour of this, but yeah we might discuss about the API some more to see whether it makes sense to keep what. I mean right now, if those parameters are not being used, sure maybe we can take them out, but I think we should look into why they were put there e.g. passing the dataStore object into the GoraMapper, is this because we can get it through the Query object? I think most of the others are a lot more straight forward.

**Comment by kamaci** [comment]
Unused method parameters may lead a potential bug. Here is a list of what I've changed:

* CassandraSuperColumn.java#getUnionIndex(String fieldName, HColumn<ByteBuffer, ByteBuffer> uc)

* QueryCounter.java#createJob(DataStore<K,T> dataStore, Query<K,T> query)

* QueryCounter.java#countQuery(DataStore<K,T> dataStore, Query<K,T> query)

* WordCount.java#createJob(DataStore<String,WebPage> inStore, Query<String,WebPage> query, DataStore<String,TokenDatum> outStore)

* GoraInputFormat.java#setInputPath(PartitionQuery<K,T> partitionQuery, TaskAttemptContext context)

* GoraInputFormat.java#setInput(Job job, Query<K1,V1> query, DataStore<K1,V1> dataStore, boolean reuseObjects)

* GoraMapper.java#initMapperJob(Job job, Query<K1,V1> query, DataStore<K1,V1> dataStore, Class<K2> outKeyClass, Class<K2> outKeyClass, Class<V2> outValueClass,  Class<? extends GoraMapper> mapperClass, Class<? extends Partitioner> partitionerClass, boolean reuseObjects)

* GoraMapper.java#initMapperJob(Job job, Query<K1,V1> query, DataStore<K1,V1> dataStore, Class<K2> outKeyClass, Class<K2> outKeyClass, Class<V2> outValueClass,  Class<? extends GoraMapper> mapperClass, boolean reuseObjects)

* IOUtils.java#serialize(OutputStream os, SpecificDatumWriter<T> datumWriter, Schema schema, T object)

* IOUtils.java#serialize(SpecificDatumWriter<T> datumWriter, Schema schema, T object)

* IOUtils.java#deserialize(InputStream is, SpecificDatumReader<T> datumReader, Schema schema, T object)

* IOUtils.java#deserialize(byte[] bytes, SpecificDatumReader<T> datumReader, Schema schema, T object)

* DataStoreTestUtil.java#createEmployee(DataStore<K, Employee> dataStore)

* DataStoreTestUtil.java#createWebPage(DataStore<K, Employee> dataStore)

* DataStoreTestUtil.java#createBoss(DataStore<K, Employee> dataStore)

* MongoMapping.java#addClassField(String docNameFromMapping, String classFieldName, String docFieldName, String fieldType)

**Comment by renato2099** [comment]
Hey @kamaci  I think I will try to respond to myself lol I think it is fine because the query object gets created by the dataStore, thus it will already contain a reference to it when passed into the MapReduce job. So I am a +1 after looking it more carefully

**Comment by lewismc** [comment]
This has been merged right?

**Pull request closed without merging**
