### PR TITLE
GORA-512 Add HBase configuration exception for erroneous mapping file and test

### PR DESCRIPTION
**Pull request by nishadi**
This PR resolves GORA-512 by adding the necessary exception for erroneous mapping files and a test case to capture it.

### CODE REVIEW

**Comment by djkevincr** [comment]
+1, Looks good. @alfonsonishikawa Can you please have a look?

**Comment by alfonsonishikawa** [comment]
@djkevincr , sure!

Looks good, test passes. I will merge in a while :)

**Comment by djkevincr** [comment]
+1

**Comment by alfonsonishikawa** [comment]
Pushed. Thank you, @nishadi !

**Comment by nishadi** [comment]
Thank you for merging :)

**Comment by renato2099** [comment]
this looks to me +1

**Pull request merged**
